### ISSUE TITLE
Animation not working anymore

### ISSUE THREAD

**Issue by DutchPete** [DubininDmitry/Obuntu#2]
Are you aware that the file explorer animation is not working anymore in v0.10.0?

**Comment by dmytrodubinin** [comment]
Thanks for your feedback. I am testing the theme on the latest stable release v0.9.22. With the release of v0.10 for all users, I will revise the animation so that it does not conflict with the new functionality of Multiselect files (if it will be possible to save it)

**Comment by captaincaed** [comment]
Hey thanks, I just found this as well.  The main issue I have is the arrows are all bunched up at the root folder.

However, I really like this theme.  I love how it emphasizes readability.  It's my current favorite.
