### ISSUE TITLE
Changing main theme color

### ISSUE THREAD

**Issue by Vladikasik** [DubininDmitry/Obuntu#7]
Is there any variant to change main red theme color to same softness blue or green color, it would be perfect.
It would be even cooler if there would be an option to choose from 3-5 main colors somewhere in settings.
I understand this request can be hard and super-individual, but we can speak about making this feature for money from me
Feel free to text me
telegram: @vladislav_ain
email: Vladislav.ainshtein@gmail.com, but telegram is better
Thanks in advance

**Comment by dmytrodubinin** [comment]
If you need to change colors in a color theme, then you are free to do it in css.
At the moment I'm only releasing breaking fixes for this color theme as I no longer use Obsidian.
