### ISSUE TITLE
Folder names move to the right when clicked

### ISSUE THREAD

**Issue by sethCodesSometimes** [DubininDmitry/Obuntu#8]

**Comment by dmytrodubinin** [comment]
Can you describe in more detail? I don't see this problem:

https://github.com/dmytrodubinin/Obuntu-theme-for-Obsidian/assets/8066458/34a6a1ff-fd7d-43ca-8785-4f62170a7103

**Comment by sethCodesSometimes** [comment]
It is only happening with child folders. Could possibly be an
incompatibility with plugins/snippets I have installed but I doubt it.

**Comment by dmytrodubinin** [comment]
Thanks for pointing out the problem.
I just update theme with fixing this issue. Please update theme and test again.
